const name = localStorage.getItem("name") || "Luc";

export const story = [
    {
        background: "./assets/img/01-forest.png",
        place: "Forêt",
        video: {
            name: "intro",
            src: "./assets/videos/intro.mp4",
        },
        text: {
            name: "intro",
            text: `Cher Hershel Layton, j'aurai une requête à vous faire. Retrouvez-moi dans mon château. -M. Reinhold`,
            achievement: {
                name: "intro",
                img: "./assets/img/player-icon.png",
                text: "Retrouvez M. Reinhold à son château.",
                goal: "Aller au château de Reinhold.",
                notes: `Le professeur a reçu une étrange lettre d'un certain M. Reinhold l'invitant à son château pour une requête, que peut-il bien se passer ?`,
            },
        },
        npc: [],
        arrows: [
            {
                condition: "puzzle-1",
                direction: "up",
                width: "6%",
                left: "55%",
                bottom: "40%",
                destination: 1,
            },
        ],
        interactions: [
            {
                bottom: "25%",
                left: "25%",
                width: "45%",
                height: "45%",
                event: {
                    ending: {
                        condition: "puzzle-1-loose",
                        title: "Fin numéro 1",
                        text: "Vous vous êtes trompés de chemin.",
                    },
                    achievement: {
                        name: "puzzle-1",
                        img: "./assets/img/player-icon.png",
                        text: "Vous connaissez le chemin à prendre.",
                        goal: "Traversez la forêt.",
                        notes: `Le professeur et ${name} ont décidés de traverser la forêt pour se rendre au château.`,
                    },
                    puzzle: {
                        number: "001",
                        name: "Les étoiles",
                        background: "./assets/img/puzzle-1.png",
                        smallDescription:
                            "4 formes dans le ciel. Trouvez leur base commune.",
                        description:
                            "4 formes se démarquent dans le ciel. On dirait que ces 4 formes sont fait à partir d'une même base. Choisissez la base qui a été utilisée pour former les 4 autres.",
                        elements: [
                            {
                                response: false,
                                width: "10%",
                                height: "15%",
                                left: "12%",
                                bottom: "30%",
                            },
                            {
                                response: false,
                                width: "10%",
                                height: "15%",
                                left: "35%",
                                bottom: "30%",
                            },
                            {
                                response: true,
                                width: "10%",
                                height: "15%",
                                left: "60%",
                                bottom: "30%",
                            },
                        ],
                    },
                    dialogue: [
                        {
                            name: name,
                            src: "./assets/img/player-dialogue.png",
                            color: "var(--linear-blue)",
                            text: `Vers où doit-on aller ?`,
                            side: "left",
                            voice: "voice2SFX",
                        },
                        {
                            name: "Layton",
                            src: "./assets/img/layton.png",
                            color: "var(--linear-green)",
                            text: `C'est une très bonne question !`,
                            side: "right",
                            voice: "voice3SFX",
                        },
                    ],
                },
            },
        ],
    },
    {
        background: "./assets/img/02-forest.png",
        place: "Forêt",
        npc: [],
        arrows: [
            {
                direction: "up",
                width: "6%",
                left: "43%",
                bottom: "55%",
                destination: 2,
            },
            {
                direction: "down",
                width: "10%",
                left: "47%",
                bottom: "5%",
                destination: 0,
            },
        ],
        interactions: [],
    },
    {
        background: "./assets/img/03-forest.png",
        place: "Forêt",
        npc: [
            {
                name: "Flora",
                src: "./assets/img/girl.png",
                width: "15%",
                left: "55%",
                bottom: "15%",
                dialogue: [
                    {
                        name: "Layton",
                        src: "./assets/img/layton.png",
                        color: "var(--linear-green)",
                        text: `Bonjour jeune fille, le Duc est-il présent au château ?`,
                        side: "left",
                        voice: "voice3SFX",
                    },
                    {
                        name: "Flora",
                        src: "./assets/img/girl-dialogue.png",
                        color: "var(--linear-pink)",
                        text: `Oui, bien sûr, continuez le chemin pour vous y rendre !`,
                        side: "right",
                        voice: "voice1SFX",
                    },
                    {
                        name: name,
                        src: "./assets/img/player-dialogue.png",
                        color: "var(--linear-blue)",
                        text: `D’accord, merci !`,
                        side: "left",
                        voice: "voice2SFX",
                    },
                ],
            },
        ],
        arrows: [
            {
                direction: "up",
                width: "7%",
                left: "35%",
                bottom: "32%",
                destination: 3,
            },
            {
                direction: "down",
                width: "9%",
                left: "47%",
                bottom: "5%",
                destination: 1,
            },
        ],
        interactions: [],
    },
    {
        background: "./assets/img/04-castle-bridge.png",
        place: "Pont du château",
        npc: [
            {
                name: "Viktor",
                src: "./assets/img/viktor.png",
                width: "15%",
                left: "20%",
                bottom: "8%",
                dialogue: [
                    {
                        name: "Layton",
                        src: "./assets/img/layton.png",
                        color: "var(--linear-green)",
                        text: `Bonsoir !`,
                        side: "left",
                        voice: "voice3SFX",
                    },
                    {
                        name: "Viktor",
                        src: "./assets/img/viktor-dialogue.png",
                        color: "var(--linear-brown)",
                        text: `Qu'est-ce que vous êtes venu faire ici ?`,
                        side: "right",
                        voice: "voice3SFX",
                    },
                    {
                        name: name,
                        src: "./assets/img/player-dialogue.png",
                        color: "var(--linear-blue)",
                        text: `On a été invité par le duc.`,
                        side: "left",
                        voice: "voice2SFX",
                    },
                    {
                        name: "Viktor",
                        src: "./assets/img/viktor-dialogue.png",
                        color: "var(--linear-brown)",
                        text: `Des invités ? Entrez donc ! Pardonnez mon impolitesse.`,
                        side: "right",
                        voice: "voice3SFX",
                    },
                    {
                        name: "Viktor",
                        src: "./assets/img/viktor-dialogue.png",
                        color: "var(--linear-brown)",
                        text: `Je m'appelle Viktor.`,
                        side: "right",
                        voice: "voice3SFX",
                    },
                    {
                        name: name,
                        src: "./assets/img/player-dialogue.png",
                        color: "var(--linear-blue)",
                        text: `Moi c'est ${name}, et à côté de moi, c'est le professeur.`,
                        side: "left",
                        voice: "voice2SFX",
                    },
                ],
            },
        ],
        arrows: [
            {
                direction: "up",
                width: "5%",
                left: "51%",
                bottom: "25%",
                destination: 4,
            },
            {
                direction: "down",
                width: "7%",
                left: "45%",
                bottom: "5%",
                destination: 2,
            },
        ],
        interactions: [],
    },
    {
        background: "./assets/img/05-castle-door.png",
        place: "Porte du château",
        npc: [],
        arrows: [
            {
                condition: "door",
                direction: "up",
                width: "7%",
                left: "46.5%",
                bottom: "35%",
                destination: 5,
            },
            {
                direction: "down",
                width: "10%",
                left: "45%",
                bottom: "5%",
                destination: 3,
            },
        ],
        interactions: [
            {
                bottom: "30%",
                left: "37%",
                width: "25%",
                height: "45%",
                event: {
                    achievement: {
                        name: "door",
                        img: "./assets/img/player-icon.png",
                        text: "La porte semble être ouverte.",
                        goal: "Entrez dans le château.",
                        notes: `Le professeur et ${name} ont décidés d'entrer dans le château.`,
                    },
                    dialogue: [
                        {
                            name: name,
                            src: "./assets/img/player-dialogue.png",
                            color: "var(--linear-blue)",
                            text: `Cet endroit fait vraiment froid dans le dos…`,
                            side: "left",
                            voice: "voice2SFX",
                        },
                        {
                            name: "Layton",
                            src: "./assets/img/layton.png",
                            color: "var(--linear-green)",
                            text: `C’est vrai mais cela ne sert à rien de se tourner les pouces ici, entrons.`,
                            side: "right",
                            voice: "voice3SFX",
                        },
                    ],
                },
            },
        ],
    },

    {
        background: "./assets/img/06-hall.png",
        place: "Hall principal",
        npc: [
            {
                name: "Reinhold",
                src: "./assets/img/reinhold.png",
                width: "20%",
                left: "65%",
                bottom: "15%",
                achievement: {
                    name: "talk-with-reinhold",
                    img: "./assets/img/player-icon.png",
                    text: "Vous décidez de visiter le château.",
                    goal: "Visitez le château.",
                    notes: `Le professeur et ${name} ont décidés de visiter le château.`,
                },
                dialogue: [
                    {
                        name: "Reinhold",
                        src: "./assets/img/reinhold-dialogue.png",
                        color: "var(--linear-brown)",
                        text: `Bien le bonsoir, je suppose que vous êtes le professeur Layton et son fameux acolyte.`,
                        side: "right",
                        voice: "voice3SFX",
                    },
                    {
                        name: "Layton",
                        src: "./assets/img/layton.png",
                        color: "var(--linear-green)",
                        text: `Nous sommes là suite à la lettre que nous avons reçu.`,
                        side: "right",
                        voice: "voice2SFX",
                    },
                    {
                        name: "Reinhold",
                        src: "./assets/img/reinhold-dialogue.png",
                        color: "var(--linear-brown)",
                        text: `Oui, je vous laisse explorer le château, nous en reparlerons juste après.`,
                        side: "right",
                        voice: "voice3SFX",
                    },
                    {
                        name: name,
                        src: "./assets/img/player-dialogue.png",
                        color: "var(--linear-blue)",
                        text: `D'accord !`,
                        side: "left",
                        voice: "voice1SFX",
                    },
                ],
            },
        ],
        arrows: [
            {
                condition: "talk-with-reinhold",
                direction: "left",
                width: "3%",
                left: "10%",
                bottom: "65%",
                destination: 6,
            },
            {
                condition: "talk-with-reinhold",
                direction: "right",
                width: "3%",
                left: "70%",
                bottom: "65%",
                destination: 7,
            },
            {
                direction: "down",
                width: "10%",
                left: "45%",
                bottom: "5%",
                destination: 4,
            },
        ],
        interactions: [],
    },
    {
        background: "./assets/img/07-hall-gauche.png",
        place: "Hall principal",
        npc: [],
        arrows: [
            {
                condition: "bedroom",
                direction: "up",
                width: "4%",
                left: "10%",
                bottom: "65%",
                destination: 13,
            },
            {
                direction: "down",
                width: "10%",
                left: "45%",
                bottom: "5%",
                destination: 5,
            },
        ],
        interactions: [
            {
                bottom: "55%",
                left: "0%",
                width: "30%",
                height: "45%",
                event: {
                    dialogue: [
                        {
                            name: "Layton",
                            src: "./assets/img/layton.png",
                            color: "var(--linear-green)",
                            text: `${name} ! Ne vas pas trop loin, on ne va pas s'aventurer dans leurs chambres !`,
                            side: "right",
                            voice: "voice3SFX",
                        },
                        {
                            name: name,
                            src: "./assets/img/player-dialogue.png",
                            color: "var(--linear-blue)",
                            text: `C'est vrai, excusez-moi professeur...`,
                            side: "left",
                            voice: "voice2SFX",
                        },
                    ],
                },
            },
        ],
    },
    {
        background: "./assets/img/09-dining-room.png",
        place: "Salle à manger",
        npc: [],
        arrows: [
            {
                condition: "secret",
                direction: "left",
                width: "5%",
                left: "15%",
                bottom: "30%",
                destination: 8,
            },
            {
                direction: "down",
                width: "10%",
                left: "45%",
                bottom: "5%",
                destination: 5,
            },
        ],
        interactions: [
            {
                bottom: "25%",
                left: "5%",
                width: "20%",
                height: "25%",
                event: {
                    achievement: {
                        name: "secret",
                        img: "./assets/img/player-icon.png",
                        text: "Vous découvrez un passage secret.",
                        goal: "Visitez le passage secret!",
                        notes: `Le professeur et ${name} ont trouvés un passage secret, qui a-t-il la dedans ?`,
                        music: "./assets/sounds/suspenseMusic.mp3",
                    },
                    dialogue: [
                        {
                            name: name,
                            src: "./assets/img/player-dialogue.png",
                            color: "var(--linear-blue)",
                            text: `Professeur, un passage secret !`,
                            side: "left",
                            voice: "voice2SFX",
                        },
                        {
                            name: "Layton",
                            src: "./assets/img/layton.png",
                            color: "var(--linear-green)",
                            text: `C'est bien curieux, allons y jeter un oeil.`,
                            side: "right",
                            voice: "voice3SFX",
                        },
                    ],
                },
            },
        ],
    },
    {
        background: "./assets/img/11-secret-room.png",
        place: "Passage secret",
        npc: [],
        arrows: [
            {
                direction: "down",
                width: "10%",
                left: "45%",
                bottom: "5%",
                destination: 9,
            },
            {
                direction: "right",
                width: "5%",
                left: "65%",
                bottom: "28%",
                destination: 7,
            },
        ],
        interactions: [],
    },
    {
        background: "./assets/img/12-secret-room.png",
        place: "Passage secret",
        npc: [],
        arrows: [
            {
                condition: "puzzle-2",
                direction: "up",
                width: "7%",
                left: "35%",
                bottom: "50%",
                destination: 10,
            },
            {
                direction: "down",
                width: "10%",
                left: "45%",
                bottom: "5%",
                destination: 8,
            },
        ],
        interactions: [
            {
                bottom: "25%",
                left: "25%",
                width: "25%",
                height: "65%",
                event: {
                    ending: {
                        condition: "puzzle-2-loose",
                        title: "Fin numéro 2",
                        text: "La porte est verrouillée à jamais.",
                    },
                    achievement: {
                        name: "puzzle-2",
                        img: "./assets/img/player-icon.png",
                        text: "Vous déverrouillez la porte !",
                        goal: "Découvrez ce qu'il y a derrière la porte!",
                        notes: `Le professeur et ${name} ont trouvés un passage secret, qui a-t-il la dedans ?`,
                        music: "./assets/sounds/suspenseMusic.mp3",
                    },
                    puzzle: {
                        number: "002",
                        name: "La porte",
                        background: "./assets/img/puzzle-2.png",
                        smallDescription:
                            "Déverrouillez la porte en trouvant la bonne valve.",
                        description:
                            "La porte est verrouillée avec un mécanisme à vapeur.</br>Les valves rouges sont fermées, les valves bleues sont ouvertes.</br>Quel conduit est celui par lequel la vapeur va passer.",
                        elements: [
                            {
                                response: false,
                                width: "10%",
                                height: "15%",
                                left: "30%",
                                bottom: "78%",
                            },
                            {
                                response: false,
                                width: "10%",
                                height: "15%",
                                left: "45%",
                                bottom: "85%",
                            },
                            {
                                response: true,
                                width: "10%",
                                height: "15%",
                                left: "58%",
                                bottom: "75%",
                            },
                        ],
                    },
                    dialogue: [
                        {
                            name: name,
                            src: "./assets/img/player-dialogue.png",
                            color: "var(--linear-blue)",
                            text: `La porte est verrouillée.`,
                            side: "left",
                            voice: "voice2SFX",
                        },
                        {
                            name: "Layton",
                            src: "./assets/img/layton.png",
                            color: "var(--linear-green)",
                            text: `Essayons de la déverrouiller !`,
                            side: "right",
                            voice: "voice3SFX",
                        },
                    ],
                },
            },
        ],
    },
    {
        background: "./assets/img/13-mine.png",
        place: "Passage secret",
        npc: [],
        arrows: [],
        interactions: [],
        video: {
            name: "badending",
            src: "./assets/videos/badending.mp4",
        },
    },
];
